### ISSUE TITLE
"bbb_user_input" data dimension error

### ISSUE THREAD

**Issue by DaiYT-Ari** [12rajnish/DeePred-BBB#7]
Hello, I am having a problem with the data dimension while running DeePred-BBB. After preparing the data in smiles.smi format, run the code, and the resulting "bbb_user_input" shape is (None, 1917), but the error message shows that the input data shape required by the model is (None, None, 1917). What can I do next?
And when loading the model, "absl:No training configuration found in the save file, so the model was *not* compiled. Compile it manually.
![QQ截图20240323123200](https://github.com/12rajnish/DeePred-BBB/assets/153923481/5729c765-c34b-4336-bca7-b42c0e55e88f)
![QQ图片20240323123410](https://github.com/12rajnish/DeePred-BBB/assets/153923481/f80c5708-4d7b-4026-9595-f422e76e6f4b)

**Comment by OliviaViessmann** [comment]
I have the same issue with the provided example `smiles.smi`
`python DeePred-BBB_Script.py`
gives 

  File "/home/pi-user/DeePred-BBB/DeePred-BBB_Script.py", line 47, in bbb
    prediction = loaded_model.predict(bbb_user_input).round()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pi-user/miniconda3/envs/deepredbbb/lib/python3.11/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/pi-user/miniconda3/envs/deepredbbb/lib/python3.11/site-packages/keras/src/models/functional.py", line 280, in _adjust_input_rank
    raise ValueError(
ValueError: Exception encountered when calling Sequential.call().

Invalid input shape for input Tensor("data:0", shape=(1, 1917), dtype=float32). Expected shape (None, None, 1917), but input has incompatible shape (1, 1917)

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=(1, 1917), dtype=float32)
  • training=False
  • mask=None


I tried reshaping `bbb_user_input = np.reshape(bbb_user_input, (bbb_user_input.shape[0], 1, bbb_user_input.shape[1]))`
but then I get errors further down the line in the model prediction, so not sure this is correct. 
Could you provide a functioning example with the code?
Thanks a lot

**Comment by jfreeze95** [comment]
Same issue here.
I tried this on a Mac ARM machine as well as a linux machine.
Attempts were made with python 3.10 and 3.11
If we look at the older commit before the QoL update, a different error is gotten that is also seen when using the SVM-BBB GitHub code you provide:
```
python3 DeePred-BBB_Script.py
Descriptor calculation completed in 0.879 secs . Average speed: 0.88 s/mol.
Features calculated
/Users/XXXX/miniconda3/envs/BBB310/lib/python3.10/site-packages/keras/src/layers/regularization/dropout.py:42: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
/Users/XXXX/miniconda3/envs/BBB310/lib/python3.10/site-packages/keras/src/layers/core/dense.py:86: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
WARNING:absl:No training configuration found in the save file, so the model was *not* compiled. Compile it manually.
Model loaded
Traceback (most recent call last):
  File "/Users/XXXX/Desktop/Research/BBB/DeePred-BBB/DeePred-BBB_Script.py", line 104, in <module>
    run_prediction(path)        
  File "/Users/XXXX/Desktop/Research/BBB/DeePred-BBB/DeePred-BBB_Script.py", line 83, in run_prediction
    pred = bbb(input_bbb)
  File "/Users/XXXX/Desktop/Research/BBB/DeePred-BBB/DeePred-BBB_Script.py", line 47, in bbb
    prediction = loaded_model.predict(bbb_user_input).round()
  File "/Users/XXXX/miniconda3/envs/BBB310/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/Users/XXXX/miniconda3/envs/BBB310/lib/python3.10/site-packages/keras/src/models/functional.py", line 285, in _adjust_input_rank
    raise ValueError(
ValueError: Exception encountered when calling Sequential.call().

Invalid input shape for input Tensor("data:0", shape=(1, 1917), dtype=float32). Expected shape (None, None, 1917), but input has incompatible shape (1, 1917)

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=(1, 1917), dtype=float32)
  • training=False
  • mask=None

```

**Comment by suryavenkatsn** [comment]
I too got the same error message. Seems like this issue is unresolved for many months. Hope to get some resolution.
